# -*- coding: utf-8 -*-
"""Week2_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLGaLnTe6EX5oMpeowhZdBQJAdL_NE0d
"""

# week 2 project
## temperature converter

print("===== TEMPERATURE CONVERTER =====")

celsius = float(input("Enter temperature in Celsius: "))

fahrenheit_answer = (celsius * 9 / 5) + 32

print(celsius, "Celsius is equal to", fahrenheit_answer, "Fahrenheit")

fahrenheit = float(input("Enter temperature in Fahrenheit: "))

celsius_answer = (fahrenheit - 32) * 5 / 9

print(fahrenheit, "Fahrenheit is equal to", celsius_answer, "Celsius")